# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apprehentice's Blog
email: apprehentice@gmail.com
description: "An alternative stream of consciousness from Apprehentice"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.appr.pro" # the base hostname & protocol for your site
twitter_username: foxtrot200
github_username:  apprehentice
timezone: America/Los_Angeles
future: true

author: Apprehentice

permalink: /:year/:month/:day/:title.html

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Build settings
markdown: kramdown

# Pagination
# pagination:
#   enabled: true
#   per_page: 10
#   permalink: '/posts/:num/'
#   title: ':title - Page :num'

paginate: 10
paginate_path: "/posts/:num/"