# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apprehentice's Blog
email: apprehentice@gmail.com
description: "An alternative stream of consciousness from Apprehentice"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://apprehentice.github.io" # the base hostname & protocol for your site
twitter_username: foxtrot200
github_username:  apprehentice
timezone: America/Los_Angeles
future: true

# Plugins
gems: [jekyll-paginate]

# Build settings
markdown: kramdown

# Pagination
paginate: 10
paginate_path: "/posts/:num/"
